import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeRegistry from "./ThemeRegistry";
import { Container } from "@mui/material";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<ThemeRegistry>
					<Container
						maxWidth='lg'
						component={"main"}
						sx={{
							minHeight: "100svh",
							display: "flex",
							alignItems: "center",
							justifyContent: "center",
						}}>
						{children}
					</Container>
				</ThemeRegistry>
			</body>
		</html>
	);
}
